version: '3.9'
services:
  web:
    build: .
    command: gunicorn stock_insight.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    ports:
      - "8000:8000"
    env_file:
      - .env
    
  telegram_bot:
    build: .
    command: python manage.py telegrambot
    volumes:
      - .:/app
    depends_on:
      - web