# Generated by Django 5.2.3 on 2025-07-03 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Insight',
                'verbose_name_plural': 'Stock Insights',
            },
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=10)),
                ('next_day_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mse', models.FloatField(help_text='Mean Squared Error')),
                ('rmse', models.FloatField(help_text='Root Mean Squared Error')),
                ('r2', models.FloatField(help_text='R-squared Score')),
                ('metrics_json', models.JSONField(default=dict, help_text='Additional metrics and model parameters in JSON format')),
                ('plot_urls', models.JSONField(default=list, help_text='List of URLs/paths to generated PNG plots')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, help_text='Actual stock price for validation (filled later)', max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
