# Generated by Django 5.2.3 on 2025-07-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockInsight',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='mse',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='r2',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='rmse',
        ),
    ]
