# Generated by Django 5.2.3 on 2025-07-04 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_request_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date of the last prediction request made by the user'),
            preserve_default=False,
        ),
    ]
