# Generated by Django 5.2.3 on 2025-07-04 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_last_request_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='telegram_user_id',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='daily_request_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of daily prediction requests made by the user'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Indicates if the user has a premium account'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_request_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date of the last prediction request made by the user'),
            preserve_default=False,
        ),
    ]
